---
server:
  servlet:
    contextPath: /financas
  port: 8088
app:
  build:
    version: '@project.version@'

jasypt:
  encryptor:
    password: sfirgni74wigtoc747f87egf06sedsff9c7ds965dvstfvsg

# logging
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
  level:
    root: INFO
    br:
      com:
        cepp:
          maps:
            financas: DEBUG

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    username: financas
    password: f1n4nc4s@123
    url: jdbc:postgresql://localhost/financas
    initializationMode: always
  jpa:
    hibernate:
      ddlAuto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    showSql: true

  jackson:
    deserialization:
      failOnUnknownProperties: true

springdoc:
  apiDocs:
    enabled: true
  packagesToScan: br.com.cepp.maps.financas.resource
  swagger-ui:
    disableSwaggerDefaultUrl: true
  writerWithDefaultPrettyPrinter: true
  defaultConsumesMediaType: application/json
  defaultProducesMediaType: application/json
