version: "3.5"

services:
  postgres:
    image: postgres:10
    container_name: postgres
    hostname: postgres
    environment:
      - POSTGRES_USER=financas
      - POSTGRES_PASSWORD=f1n4nc4s@123
      - POSTGRES_DB=financas
    ports:
      - 5432:5432
    volumes:
      - "financa-postgres:/var/lib/postgresql/data"
volumes:
  financa-postgres:
